server:
  port: 8083

spring:
  application:
    name: motorcycle-service
  config:
    import: optional:configserver:http://localhost:8085
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

