server:
  port: 8082

spring:
  application:
    name: car-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices
      database: microservices

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka