server:
  port: 8082

spring:
  application:
    name: car-service
  config:
    import: optional:configserver:http://localhost:8085
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices
      database: microservices
